// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/bbf_fiber_channelpair_body.proto

package bbf_fiber

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChannelpairConfigData struct {
	ChannelgroupRef      string            `protobuf:"bytes,1,opt,name=channelgroup_ref,json=channelgroupRef,proto3" json:"channelgroup_ref,omitempty"`
	ChannelpartitionRef  string            `protobuf:"bytes,2,opt,name=channelpartition_ref,json=channelpartitionRef,proto3" json:"channelpartition_ref,omitempty"`
	ChannelpairType      string            `protobuf:"bytes,3,opt,name=channelpair_type,json=channelpairType,proto3" json:"channelpair_type,omitempty"`
	ChannelpairLinerate  string            `protobuf:"bytes,4,opt,name=channelpair_linerate,json=channelpairLinerate,proto3" json:"channelpair_linerate,omitempty"`
	GponPonidInterval    uint32            `protobuf:"varint,5,opt,name=gpon_ponid_interval,json=gponPonidInterval,proto3" json:"gpon_ponid_interval,omitempty"`
	GponPonidOdnClass    PonIdOdnClassType `protobuf:"varint,6,opt,name=gpon_ponid_odn_class,json=gponPonidOdnClass,proto3,enum=bbf_fiber_types.PonIdOdnClassType" json:"gpon_ponid_odn_class,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChannelpairConfigData) Reset()         { *m = ChannelpairConfigData{} }
func (m *ChannelpairConfigData) String() string { return proto.CompactTextString(m) }
func (*ChannelpairConfigData) ProtoMessage()    {}
func (*ChannelpairConfigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e895fd86e230925f, []int{0}
}

func (m *ChannelpairConfigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelpairConfigData.Unmarshal(m, b)
}
func (m *ChannelpairConfigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelpairConfigData.Marshal(b, m, deterministic)
}
func (m *ChannelpairConfigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelpairConfigData.Merge(m, src)
}
func (m *ChannelpairConfigData) XXX_Size() int {
	return xxx_messageInfo_ChannelpairConfigData.Size(m)
}
func (m *ChannelpairConfigData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelpairConfigData.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelpairConfigData proto.InternalMessageInfo

func (m *ChannelpairConfigData) GetChannelgroupRef() string {
	if m != nil {
		return m.ChannelgroupRef
	}
	return ""
}

func (m *ChannelpairConfigData) GetChannelpartitionRef() string {
	if m != nil {
		return m.ChannelpartitionRef
	}
	return ""
}

func (m *ChannelpairConfigData) GetChannelpairType() string {
	if m != nil {
		return m.ChannelpairType
	}
	return ""
}

func (m *ChannelpairConfigData) GetChannelpairLinerate() string {
	if m != nil {
		return m.ChannelpairLinerate
	}
	return ""
}

func (m *ChannelpairConfigData) GetGponPonidInterval() uint32 {
	if m != nil {
		return m.GponPonidInterval
	}
	return 0
}

func (m *ChannelpairConfigData) GetGponPonidOdnClass() PonIdOdnClassType {
	if m != nil {
		return m.GponPonidOdnClass
	}
	return PonIdOdnClassType_CLASS_A
}

type ChannelpairOperData struct {
	ActualDownstreamLambda uint32   `protobuf:"varint,1,opt,name=actual_downstream_lambda,json=actualDownstreamLambda,proto3" json:"actual_downstream_lambda,omitempty"`
	PrimaryCtAssigned      bool     `protobuf:"varint,2,opt,name=primary_ct_assigned,json=primaryCtAssigned,proto3" json:"primary_ct_assigned,omitempty"`
	SecondaryCtAssigned    bool     `protobuf:"varint,3,opt,name=secondary_ct_assigned,json=secondaryCtAssigned,proto3" json:"secondary_ct_assigned,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ChannelpairOperData) Reset()         { *m = ChannelpairOperData{} }
func (m *ChannelpairOperData) String() string { return proto.CompactTextString(m) }
func (*ChannelpairOperData) ProtoMessage()    {}
func (*ChannelpairOperData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e895fd86e230925f, []int{1}
}

func (m *ChannelpairOperData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelpairOperData.Unmarshal(m, b)
}
func (m *ChannelpairOperData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelpairOperData.Marshal(b, m, deterministic)
}
func (m *ChannelpairOperData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelpairOperData.Merge(m, src)
}
func (m *ChannelpairOperData) XXX_Size() int {
	return xxx_messageInfo_ChannelpairOperData.Size(m)
}
func (m *ChannelpairOperData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelpairOperData.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelpairOperData proto.InternalMessageInfo

func (m *ChannelpairOperData) GetActualDownstreamLambda() uint32 {
	if m != nil {
		return m.ActualDownstreamLambda
	}
	return 0
}

func (m *ChannelpairOperData) GetPrimaryCtAssigned() bool {
	if m != nil {
		return m.PrimaryCtAssigned
	}
	return false
}

func (m *ChannelpairOperData) GetSecondaryCtAssigned() bool {
	if m != nil {
		return m.SecondaryCtAssigned
	}
	return false
}

func init() {
	proto.RegisterType((*ChannelpairConfigData)(nil), "bbf_fiber.ChannelpairConfigData")
	proto.RegisterType((*ChannelpairOperData)(nil), "bbf_fiber.ChannelpairOperData")
}

func init() {
	proto.RegisterFile("voltha_protos/bbf_fiber_channelpair_body.proto", fileDescriptor_e895fd86e230925f)
}

var fileDescriptor_e895fd86e230925f = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x6f, 0xd4, 0x30,
	0x10, 0x85, 0x95, 0x16, 0x2a, 0x6a, 0xa9, 0x40, 0xb3, 0x2d, 0x8a, 0x38, 0xad, 0x96, 0xcb, 0x72,
	0x68, 0x56, 0x2d, 0x42, 0x70, 0x85, 0xed, 0xa5, 0x52, 0xa5, 0x56, 0x81, 0x13, 0x17, 0x6b, 0x1c,
	0x3b, 0xe9, 0x88, 0xec, 0xd8, 0xb2, 0xdd, 0x45, 0xf9, 0x5d, 0xfc, 0x19, 0x7e, 0x0e, 0xb2, 0x13,
	0x92, 0x34, 0x12, 0xd7, 0xf9, 0xde, 0x7b, 0x1e, 0x3f, 0x0d, 0xcb, 0xf7, 0xba, 0xf1, 0x0f, 0xc0,
	0x8d, 0xd5, 0x5e, 0xbb, 0x8d, 0x10, 0x15, 0xaf, 0x50, 0x28, 0xcb, 0xcb, 0x07, 0x20, 0x52, 0x8d,
	0x01, 0xb4, 0x5c, 0x68, 0xd9, 0xe6, 0x51, 0x91, 0x1e, 0x0f, 0x8a, 0xb7, 0xef, 0xfe, 0x67, 0xf5,
	0xad, 0x51, 0xae, 0xd3, 0xaf, 0xfe, 0x1c, 0xb0, 0xf3, 0xed, 0x18, 0xb5, 0xd5, 0x54, 0x61, 0x7d,
	0x0d, 0x1e, 0xd2, 0xf7, 0xec, 0x75, 0xff, 0x46, 0x6d, 0xf5, 0xa3, 0xe1, 0x56, 0x55, 0x59, 0xb2,
	0x4c, 0xd6, 0xc7, 0xc5, 0xab, 0xe9, 0xbc, 0x50, 0x55, 0x7a, 0xc9, 0xce, 0x86, 0x75, 0xac, 0x47,
	0x8f, 0x9a, 0xa2, 0xfc, 0x20, 0xca, 0x17, 0x73, 0x16, 0x2c, 0x63, 0x7a, 0xfc, 0x41, 0x58, 0x29,
	0x3b, 0x7c, 0x92, 0x1e, 0xe6, 0xdf, 0x5b, 0xa3, 0x9e, 0xa4, 0xa3, 0xe5, 0x0d, 0x92, 0xb2, 0xe0,
	0x55, 0xf6, 0x6c, 0x96, 0x8e, 0xf6, 0xb6, 0x47, 0x69, 0xce, 0x16, 0xb5, 0xd1, 0xc4, 0x8d, 0x26,
	0x94, 0x1c, 0xc9, 0x2b, 0xbb, 0x87, 0x26, 0x7b, 0xbe, 0x4c, 0xd6, 0x27, 0xc5, 0x69, 0x40, 0xf7,
	0x81, 0xdc, 0xf4, 0x20, 0xfd, 0xc6, 0xce, 0x26, 0x7a, 0x2d, 0x89, 0x97, 0x0d, 0x38, 0x97, 0x1d,
	0x2d, 0x93, 0xf5, 0xcb, 0xab, 0x55, 0x3e, 0xef, 0xee, 0x5e, 0xd3, 0x8d, 0xbc, 0x93, 0xb4, 0x0d,
	0xaa, 0xb0, 0xe4, 0x24, 0xf4, 0xdf, 0x78, 0xf5, 0x3b, 0x61, 0x8b, 0x49, 0xb5, 0x77, 0x46, 0xd9,
	0x58, 0xec, 0x67, 0x96, 0x41, 0xe9, 0x1f, 0xa1, 0xe1, 0x52, 0xff, 0x22, 0xe7, 0xad, 0x82, 0x1d,
	0x6f, 0x60, 0x27, 0x24, 0xc4, 0x82, 0x4f, 0x8a, 0x37, 0x1d, 0xbf, 0x1e, 0xf0, 0x6d, 0xa4, 0xe1,
	0x5b, 0xc6, 0xe2, 0x0e, 0x6c, 0xcb, 0x4b, 0xcf, 0xc1, 0x39, 0xac, 0x49, 0xc9, 0x58, 0xf3, 0x8b,
	0xe2, 0xb4, 0x47, 0x5b, 0xff, 0xa5, 0x07, 0xe9, 0x15, 0x3b, 0x77, 0xaa, 0xd4, 0x24, 0xe7, 0x8e,
	0xc3, 0xe8, 0x58, 0x0c, 0x70, 0xf4, 0x7c, 0xfd, 0xf4, 0xe3, 0x63, 0xad, 0xcd, 0xcf, 0x3a, 0x47,
	0xda, 0x48, 0x01, 0x48, 0xc2, 0xe2, 0x45, 0x89, 0x8a, 0x60, 0xd3, 0xdd, 0xd3, 0x45, 0x77, 0x4f,
	0xf9, 0xfe, 0x72, 0x53, 0xeb, 0xf1, 0xaa, 0xc4, 0x51, 0x9c, 0x7f, 0xf8, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x12, 0xff, 0xf4, 0x8c, 0xb2, 0x02, 0x00, 0x00,
}
