// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/bbf_fiber_gemport_body.proto

package bbf_fiber

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "gopkg.in/dbainbri-ciena/voltha-protos.v1/go/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GemportsConfigData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ItfRef               string   `protobuf:"bytes,3,opt,name=itf_ref,json=itfRef,proto3" json:"itf_ref,omitempty"`
	TrafficClass         uint32   `protobuf:"varint,4,opt,name=traffic_class,json=trafficClass,proto3" json:"traffic_class,omitempty"`
	AesIndicator         bool     `protobuf:"varint,5,opt,name=aes_indicator,json=aesIndicator,proto3" json:"aes_indicator,omitempty"`
	TcontRef             string   `protobuf:"bytes,6,opt,name=tcont_ref,json=tcontRef,proto3" json:"tcont_ref,omitempty"`
	GemportId            uint32   `protobuf:"varint,7,opt,name=gemport_id,json=gemportId,proto3" json:"gemport_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GemportsConfigData) Reset()         { *m = GemportsConfigData{} }
func (m *GemportsConfigData) String() string { return proto.CompactTextString(m) }
func (*GemportsConfigData) ProtoMessage()    {}
func (*GemportsConfigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebce82f415fe9d29, []int{0}
}

func (m *GemportsConfigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GemportsConfigData.Unmarshal(m, b)
}
func (m *GemportsConfigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GemportsConfigData.Marshal(b, m, deterministic)
}
func (m *GemportsConfigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GemportsConfigData.Merge(m, src)
}
func (m *GemportsConfigData) XXX_Size() int {
	return xxx_messageInfo_GemportsConfigData.Size(m)
}
func (m *GemportsConfigData) XXX_DiscardUnknown() {
	xxx_messageInfo_GemportsConfigData.DiscardUnknown(m)
}

var xxx_messageInfo_GemportsConfigData proto.InternalMessageInfo

func (m *GemportsConfigData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GemportsConfigData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GemportsConfigData) GetItfRef() string {
	if m != nil {
		return m.ItfRef
	}
	return ""
}

func (m *GemportsConfigData) GetTrafficClass() uint32 {
	if m != nil {
		return m.TrafficClass
	}
	return 0
}

func (m *GemportsConfigData) GetAesIndicator() bool {
	if m != nil {
		return m.AesIndicator
	}
	return false
}

func (m *GemportsConfigData) GetTcontRef() string {
	if m != nil {
		return m.TcontRef
	}
	return ""
}

func (m *GemportsConfigData) GetGemportId() uint32 {
	if m != nil {
		return m.GemportId
	}
	return 0
}

type GemportsOperData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GemportId            uint32   `protobuf:"varint,3,opt,name=gemport_id,json=gemportId,proto3" json:"gemport_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GemportsOperData) Reset()         { *m = GemportsOperData{} }
func (m *GemportsOperData) String() string { return proto.CompactTextString(m) }
func (*GemportsOperData) ProtoMessage()    {}
func (*GemportsOperData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebce82f415fe9d29, []int{1}
}

func (m *GemportsOperData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GemportsOperData.Unmarshal(m, b)
}
func (m *GemportsOperData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GemportsOperData.Marshal(b, m, deterministic)
}
func (m *GemportsOperData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GemportsOperData.Merge(m, src)
}
func (m *GemportsOperData) XXX_Size() int {
	return xxx_messageInfo_GemportsOperData.Size(m)
}
func (m *GemportsOperData) XXX_DiscardUnknown() {
	xxx_messageInfo_GemportsOperData.DiscardUnknown(m)
}

var xxx_messageInfo_GemportsOperData proto.InternalMessageInfo

func (m *GemportsOperData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GemportsOperData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GemportsOperData) GetGemportId() uint32 {
	if m != nil {
		return m.GemportId
	}
	return 0
}

func init() {
	proto.RegisterType((*GemportsConfigData)(nil), "bbf_fiber.GemportsConfigData")
	proto.RegisterType((*GemportsOperData)(nil), "bbf_fiber.GemportsOperData")
}

func init() {
	proto.RegisterFile("voltha_protos/bbf_fiber_gemport_body.proto", fileDescriptor_ebce82f415fe9d29)
}

var fileDescriptor_ebce82f415fe9d29 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcf, 0x4a, 0x33, 0x31,
	0x14, 0xc5, 0x99, 0xfe, 0x9f, 0xd0, 0xc2, 0x47, 0xe0, 0xc3, 0x50, 0x29, 0x94, 0xba, 0x19, 0x84,
	0x76, 0x10, 0x11, 0xf7, 0xad, 0x20, 0x5d, 0x09, 0xb3, 0x14, 0x21, 0xdc, 0x4c, 0x92, 0xf1, 0x62,
	0x9b, 0x0c, 0x99, 0x50, 0xf0, 0x21, 0x7d, 0x05, 0xd7, 0x3e, 0x81, 0x6b, 0x99, 0x4c, 0xab, 0x56,
	0x70, 0xe1, 0x2e, 0xfc, 0xce, 0xcd, 0x39, 0xb9, 0x39, 0xe4, 0x7c, 0x67, 0x37, 0xfe, 0x11, 0x78,
	0xe9, 0xac, 0xb7, 0x55, 0x2a, 0x84, 0xe6, 0x1a, 0x85, 0x72, 0xbc, 0x50, 0xdb, 0xd2, 0x3a, 0xcf,
	0x85, 0x95, 0xcf, 0x8b, 0xa0, 0xd2, 0xf8, 0x53, 0x1d, 0xb3, 0xe3, 0x6b, 0x5b, 0xe5, 0xa1, 0x19,
	0x1a, 0x27, 0xbf, 0x19, 0xfa, 0xdc, 0x9a, 0xef, 0x76, 0xb3, 0xd7, 0x88, 0xd0, 0xdb, 0x26, 0xa5,
	0x5a, 0x59, 0xa3, 0xb1, 0xb8, 0x01, 0x0f, 0xf4, 0x3f, 0x69, 0xa1, 0x64, 0xd1, 0x34, 0x4a, 0xe2,
	0x65, 0xf7, 0xed, 0xfd, 0x65, 0x12, 0x65, 0x2d, 0x94, 0x94, 0x92, 0x8e, 0x81, 0xad, 0x62, 0xad,
	0x5a, 0xc8, 0xc2, 0x99, 0x9e, 0x90, 0x3e, 0x7a, 0xcd, 0x9d, 0xd2, 0xac, 0x1d, 0x70, 0x0f, 0xbd,
	0xce, 0x94, 0xa6, 0x67, 0x64, 0xe4, 0x1d, 0x68, 0x8d, 0x39, 0xcf, 0x37, 0x50, 0x55, 0xac, 0x33,
	0x8d, 0x92, 0x51, 0x36, 0xdc, 0xc3, 0x55, 0xcd, 0xea, 0x21, 0x50, 0x15, 0x47, 0x23, 0x31, 0x07,
	0x6f, 0x1d, 0xeb, 0x4e, 0xa3, 0x64, 0x90, 0x0d, 0x41, 0x55, 0xeb, 0x03, 0xa3, 0xa7, 0x24, 0x6e,
	0x1e, 0x5e, 0x87, 0xf4, 0x42, 0xc8, 0x20, 0x80, 0x3a, 0x66, 0x42, 0xc8, 0xe1, 0x9b, 0x50, 0xb2,
	0x7e, 0xc8, 0x88, 0xf7, 0x64, 0x2d, 0x67, 0x0f, 0xe4, 0xdf, 0x61, 0xbf, 0xbb, 0x52, 0xb9, 0xbf,
	0x6e, 0x77, 0xec, 0xde, 0xfe, 0xe1, 0xbe, 0xbc, 0xbe, 0xbf, 0x2a, 0x6c, 0xf9, 0x54, 0x2c, 0xd0,
	0xa4, 0x52, 0x00, 0x1a, 0xe1, 0x70, 0x9e, 0xa3, 0x32, 0x90, 0x36, 0x15, 0xcc, 0x9b, 0x0a, 0x16,
	0xbb, 0x8b, 0xb4, 0xb0, 0x5f, 0x45, 0x88, 0x5e, 0xe0, 0x97, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xa5, 0x7b, 0xc6, 0x25, 0xfb, 0x01, 0x00, 0x00,
}
