// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/bbf_fiber_ontani_body.proto

package bbf_fiber

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OntaniConfigData struct {
	UpstreamFecIndicator    bool     `protobuf:"varint,1,opt,name=upstream_fec_indicator,json=upstreamFecIndicator,proto3" json:"upstream_fec_indicator,omitempty"`
	MgntGemportAesIndicator bool     `protobuf:"varint,2,opt,name=mgnt_gemport_aes_indicator,json=mgntGemportAesIndicator,proto3" json:"mgnt_gemport_aes_indicator,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *OntaniConfigData) Reset()         { *m = OntaniConfigData{} }
func (m *OntaniConfigData) String() string { return proto.CompactTextString(m) }
func (*OntaniConfigData) ProtoMessage()    {}
func (*OntaniConfigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73c5154dd5f8d6b, []int{0}
}

func (m *OntaniConfigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OntaniConfigData.Unmarshal(m, b)
}
func (m *OntaniConfigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OntaniConfigData.Marshal(b, m, deterministic)
}
func (m *OntaniConfigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OntaniConfigData.Merge(m, src)
}
func (m *OntaniConfigData) XXX_Size() int {
	return xxx_messageInfo_OntaniConfigData.Size(m)
}
func (m *OntaniConfigData) XXX_DiscardUnknown() {
	xxx_messageInfo_OntaniConfigData.DiscardUnknown(m)
}

var xxx_messageInfo_OntaniConfigData proto.InternalMessageInfo

func (m *OntaniConfigData) GetUpstreamFecIndicator() bool {
	if m != nil {
		return m.UpstreamFecIndicator
	}
	return false
}

func (m *OntaniConfigData) GetMgntGemportAesIndicator() bool {
	if m != nil {
		return m.MgntGemportAesIndicator
	}
	return false
}

type OntaniOperData struct {
	OnuId                uint32   `protobuf:"varint,1,opt,name=onu_id,json=onuId,proto3" json:"onu_id,omitempty"`
	ChannelPartitionId   uint32   `protobuf:"varint,2,opt,name=channel_partition_id,json=channelPartitionId,proto3" json:"channel_partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OntaniOperData) Reset()         { *m = OntaniOperData{} }
func (m *OntaniOperData) String() string { return proto.CompactTextString(m) }
func (*OntaniOperData) ProtoMessage()    {}
func (*OntaniOperData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73c5154dd5f8d6b, []int{1}
}

func (m *OntaniOperData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OntaniOperData.Unmarshal(m, b)
}
func (m *OntaniOperData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OntaniOperData.Marshal(b, m, deterministic)
}
func (m *OntaniOperData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OntaniOperData.Merge(m, src)
}
func (m *OntaniOperData) XXX_Size() int {
	return xxx_messageInfo_OntaniOperData.Size(m)
}
func (m *OntaniOperData) XXX_DiscardUnknown() {
	xxx_messageInfo_OntaniOperData.DiscardUnknown(m)
}

var xxx_messageInfo_OntaniOperData proto.InternalMessageInfo

func (m *OntaniOperData) GetOnuId() uint32 {
	if m != nil {
		return m.OnuId
	}
	return 0
}

func (m *OntaniOperData) GetChannelPartitionId() uint32 {
	if m != nil {
		return m.ChannelPartitionId
	}
	return 0
}

func init() {
	proto.RegisterType((*OntaniConfigData)(nil), "bbf_fiber.OntaniConfigData")
	proto.RegisterType((*OntaniOperData)(nil), "bbf_fiber.OntaniOperData")
}

func init() {
	proto.RegisterFile("voltha_protos/bbf_fiber_ontani_body.proto", fileDescriptor_b73c5154dd5f8d6b)
}

var fileDescriptor_b73c5154dd5f8d6b = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4b, 0x4b, 0xc3, 0x50,
	0x10, 0x85, 0x49, 0xc1, 0xa2, 0x17, 0x14, 0x09, 0xf5, 0x81, 0x2b, 0xe9, 0x4a, 0x17, 0x6d, 0x04,
	0x8b, 0x1b, 0x57, 0x3e, 0x50, 0xb2, 0xaa, 0x74, 0xa7, 0x9b, 0xcb, 0xdc, 0x47, 0x92, 0x81, 0x66,
	0x26, 0xdc, 0x4c, 0x04, 0x7f, 0x80, 0xff, 0x5b, 0x7a, 0xd3, 0xd4, 0x6e, 0xe7, 0xfb, 0x0e, 0x73,
	0x38, 0xea, 0xf6, 0x9b, 0xd7, 0x52, 0x81, 0x6e, 0x02, 0x0b, 0xb7, 0x99, 0x31, 0x85, 0x2e, 0xd0,
	0xf8, 0xa0, 0x99, 0x04, 0x08, 0xb5, 0x61, 0xf7, 0x33, 0x8f, 0x30, 0x3d, 0xda, 0xc1, 0xe9, 0x6f,
	0xa2, 0x4e, 0x97, 0x51, 0x78, 0x61, 0x2a, 0xb0, 0x7c, 0x05, 0x81, 0x74, 0xa1, 0xce, 0xbb, 0xa6,
	0x95, 0xe0, 0xa1, 0xd6, 0x85, 0xb7, 0x1a, 0xc9, 0xa1, 0x05, 0xe1, 0x70, 0x99, 0x5c, 0x27, 0x37,
	0x87, 0xab, 0xc9, 0x40, 0xdf, 0xbc, 0xcd, 0x07, 0x96, 0x3e, 0xaa, 0xab, 0xba, 0x24, 0xd1, 0xa5,
	0xaf, 0x1b, 0x0e, 0xa2, 0xc1, 0xb7, 0x7b, 0xc9, 0x51, 0x4c, 0x5e, 0x6c, 0x8c, 0xf7, 0x5e, 0x78,
	0xf2, 0xed, 0x2e, 0x3c, 0xfd, 0x54, 0x27, 0x7d, 0x8d, 0x65, 0xe3, 0x43, 0x2c, 0x71, 0xa6, 0xc6,
	0x4c, 0x9d, 0x46, 0x17, 0x9f, 0x1e, 0xaf, 0x0e, 0x98, 0xba, 0xdc, 0xa5, 0x77, 0x6a, 0x62, 0x2b,
	0x20, 0xf2, 0x6b, 0xdd, 0x40, 0x10, 0x14, 0x64, 0xda, 0x48, 0xa3, 0x28, 0xa5, 0x5b, 0xf6, 0x31,
	0xa0, 0xdc, 0x3d, 0x3f, 0x7c, 0x2d, 0x4a, 0x94, 0xaa, 0x33, 0x73, 0xcb, 0x75, 0xe6, 0x0c, 0x20,
	0x99, 0x80, 0x33, 0x8b, 0x9e, 0x20, 0xeb, 0x47, 0x9b, 0x6d, 0x47, 0x2b, 0xf9, 0x7f, 0x37, 0x33,
	0x8e, 0xc7, 0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x0a, 0xed, 0x59, 0x59, 0x01, 0x00,
	0x00,
}
