// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/adapter.proto

package voltha

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	common "gopkg.in/dbainbri-ciena/voltha-protos.v1/go/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdapterConfig struct {
	// Common adapter config attributes here
	LogLevel common.LogLevel_LogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=voltha.LogLevel_LogLevel" json:"log_level,omitempty"`
	// Custom (vendor-specific) configuration attributes
	AdditionalConfig     *any.Any `protobuf:"bytes,64,opt,name=additional_config,json=additionalConfig,proto3" json:"additional_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdapterConfig) Reset()         { *m = AdapterConfig{} }
func (m *AdapterConfig) String() string { return proto.CompactTextString(m) }
func (*AdapterConfig) ProtoMessage()    {}
func (*AdapterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e998ce153307274, []int{0}
}

func (m *AdapterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdapterConfig.Unmarshal(m, b)
}
func (m *AdapterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdapterConfig.Marshal(b, m, deterministic)
}
func (m *AdapterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdapterConfig.Merge(m, src)
}
func (m *AdapterConfig) XXX_Size() int {
	return xxx_messageInfo_AdapterConfig.Size(m)
}
func (m *AdapterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AdapterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AdapterConfig proto.InternalMessageInfo

func (m *AdapterConfig) GetLogLevel() common.LogLevel_LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return common.LogLevel_DEBUG
}

func (m *AdapterConfig) GetAdditionalConfig() *any.Any {
	if m != nil {
		return m.AdditionalConfig
	}
	return nil
}

// Adapter (software plugin)
type Adapter struct {
	// Unique name of adapter, matching the python package name under
	// voltha/adapters.
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vendor  string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Adapter configuration
	Config *AdapterConfig `protobuf:"bytes,16,opt,name=config,proto3" json:"config,omitempty"`
	// Custom descriptors and custom configuration
	AdditionalDescription *any.Any `protobuf:"bytes,64,opt,name=additional_description,json=additionalDescription,proto3" json:"additional_description,omitempty"`
	LogicalDeviceIds      []string `protobuf:"bytes,4,rep,name=logical_device_ids,json=logicalDeviceIds,proto3" json:"logical_device_ids,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Adapter) Reset()         { *m = Adapter{} }
func (m *Adapter) String() string { return proto.CompactTextString(m) }
func (*Adapter) ProtoMessage()    {}
func (*Adapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e998ce153307274, []int{1}
}

func (m *Adapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Adapter.Unmarshal(m, b)
}
func (m *Adapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Adapter.Marshal(b, m, deterministic)
}
func (m *Adapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Adapter.Merge(m, src)
}
func (m *Adapter) XXX_Size() int {
	return xxx_messageInfo_Adapter.Size(m)
}
func (m *Adapter) XXX_DiscardUnknown() {
	xxx_messageInfo_Adapter.DiscardUnknown(m)
}

var xxx_messageInfo_Adapter proto.InternalMessageInfo

func (m *Adapter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Adapter) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Adapter) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Adapter) GetConfig() *AdapterConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Adapter) GetAdditionalDescription() *any.Any {
	if m != nil {
		return m.AdditionalDescription
	}
	return nil
}

func (m *Adapter) GetLogicalDeviceIds() []string {
	if m != nil {
		return m.LogicalDeviceIds
	}
	return nil
}

type Adapters struct {
	Items                []*Adapter `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Adapters) Reset()         { *m = Adapters{} }
func (m *Adapters) String() string { return proto.CompactTextString(m) }
func (*Adapters) ProtoMessage()    {}
func (*Adapters) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e998ce153307274, []int{2}
}

func (m *Adapters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Adapters.Unmarshal(m, b)
}
func (m *Adapters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Adapters.Marshal(b, m, deterministic)
}
func (m *Adapters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Adapters.Merge(m, src)
}
func (m *Adapters) XXX_Size() int {
	return xxx_messageInfo_Adapters.Size(m)
}
func (m *Adapters) XXX_DiscardUnknown() {
	xxx_messageInfo_Adapters.DiscardUnknown(m)
}

var xxx_messageInfo_Adapters proto.InternalMessageInfo

func (m *Adapters) GetItems() []*Adapter {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*AdapterConfig)(nil), "voltha.AdapterConfig")
	proto.RegisterType((*Adapter)(nil), "voltha.Adapter")
	proto.RegisterType((*Adapters)(nil), "voltha.Adapters")
}

func init() { proto.RegisterFile("voltha_protos/adapter.proto", fileDescriptor_7e998ce153307274) }

var fileDescriptor_7e998ce153307274 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xb1, 0xae, 0xd3, 0x30,
	0x18, 0x85, 0x95, 0x94, 0x9b, 0x7b, 0xeb, 0x0a, 0x28, 0x16, 0x45, 0x69, 0x51, 0x45, 0x54, 0x09,
	0x29, 0x03, 0x75, 0xd4, 0x80, 0x98, 0x69, 0xe9, 0x82, 0xd4, 0x29, 0x23, 0x4b, 0xe4, 0xc4, 0xae,
	0xb1, 0x70, 0xfc, 0x47, 0x49, 0x88, 0xd4, 0x57, 0x60, 0xe3, 0xc1, 0x78, 0x0f, 0x9e, 0x80, 0x19,
	0xd5, 0x76, 0x68, 0xcb, 0xc0, 0x66, 0x9f, 0xef, 0x3f, 0x3e, 0xe7, 0x8f, 0x82, 0x5e, 0xf6, 0xa0,
	0xba, 0x2f, 0x34, 0xaf, 0x1b, 0xe8, 0xa0, 0x4d, 0x28, 0xa3, 0x75, 0xc7, 0x1b, 0x62, 0xae, 0x38,
	0xb0, 0x70, 0x31, 0x17, 0x00, 0x42, 0xf1, 0xc4, 0xa8, 0xc5, 0xb7, 0x63, 0x42, 0xf5, 0xc9, 0x8e,
	0x2c, 0x16, 0xb7, 0xfe, 0x12, 0xaa, 0x0a, 0xb4, 0x63, 0xe1, 0x2d, 0xab, 0x78, 0x47, 0x2d, 0x59,
	0x7d, 0xf7, 0xd0, 0xe3, 0xad, 0x8d, 0xfa, 0x08, 0xfa, 0x28, 0x05, 0x7e, 0x8f, 0xc6, 0x0a, 0x44,
	0xae, 0x78, 0xcf, 0x55, 0xe8, 0x45, 0x5e, 0xfc, 0x24, 0x9d, 0x13, 0xeb, 0x27, 0x07, 0x10, 0x87,
	0xb3, 0xfe, 0xf7, 0x90, 0x3d, 0x28, 0x77, 0xc2, 0x5b, 0xf4, 0x8c, 0x32, 0x26, 0x3b, 0x09, 0x9a,
	0xaa, 0xbc, 0x34, 0x8f, 0x85, 0x1f, 0x22, 0x2f, 0x9e, 0xa4, 0xcf, 0x89, 0xad, 0x4d, 0x86, 0xda,
	0x64, 0xab, 0x4f, 0xd9, 0xf4, 0x32, 0x6e, 0xa3, 0x57, 0x3f, 0x7c, 0x74, 0xef, 0xca, 0xe0, 0x19,
	0xf2, 0x25, 0x33, 0xf9, 0xe3, 0xdd, 0xdd, 0xaf, 0xdf, 0x3f, 0x97, 0x5e, 0xe6, 0x4b, 0x86, 0x97,
	0x28, 0xe8, 0xb9, 0x66, 0xd0, 0x84, 0xfe, 0x35, 0x72, 0x22, 0x7e, 0x85, 0xee, 0x7b, 0xde, 0xb4,
	0x12, 0x74, 0x38, 0xba, 0xe6, 0x83, 0x8a, 0xd7, 0x28, 0x70, 0xd5, 0xa6, 0xa6, 0xda, 0x6c, 0x58,
	0xed, 0xe6, 0x23, 0x64, 0x6e, 0x08, 0x67, 0xe8, 0xc5, 0xd5, 0x52, 0x8c, 0xb7, 0x65, 0x23, 0xeb,
	0xf3, 0xed, 0x7f, 0x9b, 0x0d, 0xa1, 0xb3, 0x8b, 0x75, 0x7f, 0x71, 0xe2, 0x37, 0x08, 0x2b, 0x10,
	0xb2, 0x34, 0x0f, 0xf6, 0xb2, 0xe4, 0xb9, 0x64, 0x6d, 0xf8, 0x28, 0x1a, 0xc5, 0xe3, 0x6c, 0xea,
	0xc8, 0xde, 0x80, 0x4f, 0xac, 0x5d, 0x6d, 0xd0, 0x83, 0xab, 0xd6, 0xe2, 0xd7, 0xe8, 0x4e, 0x76,
	0xbc, 0x6a, 0x43, 0x2f, 0x1a, 0xc5, 0x93, 0xf4, 0xe9, 0x3f, 0xdd, 0x33, 0x4b, 0x77, 0xef, 0x3e,
	0xa7, 0x02, 0xea, 0xaf, 0x82, 0x48, 0x9d, 0xb0, 0x82, 0x4a, 0x5d, 0x34, 0x72, 0x5d, 0x4a, 0xae,
	0x69, 0x62, 0x0d, 0x6b, 0xfb, 0x1f, 0x90, 0x7e, 0x93, 0x08, 0x70, 0x5a, 0x11, 0x18, 0xf1, 0xed,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xb1, 0xfa, 0xb0, 0x88, 0x02, 0x00, 0x00,
}
