// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/events.proto

package voltha

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "gopkg.in/dbainbri-ciena/voltha-protos.v1/go/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigEventType_ConfigEventType int32

const (
	ConfigEventType_add    ConfigEventType_ConfigEventType = 0
	ConfigEventType_remove ConfigEventType_ConfigEventType = 1
	ConfigEventType_update ConfigEventType_ConfigEventType = 2
)

var ConfigEventType_ConfigEventType_name = map[int32]string{
	0: "add",
	1: "remove",
	2: "update",
}

var ConfigEventType_ConfigEventType_value = map[string]int32{
	"add":    0,
	"remove": 1,
	"update": 2,
}

func (x ConfigEventType_ConfigEventType) String() string {
	return proto.EnumName(ConfigEventType_ConfigEventType_name, int32(x))
}

func (ConfigEventType_ConfigEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{0, 0}
}

type KpiEventType_KpiEventType int32

const (
	KpiEventType_slice KpiEventType_KpiEventType = 0
	KpiEventType_ts    KpiEventType_KpiEventType = 1
)

var KpiEventType_KpiEventType_name = map[int32]string{
	0: "slice",
	1: "ts",
}

var KpiEventType_KpiEventType_value = map[string]int32{
	"slice": 0,
	"ts":    1,
}

func (x KpiEventType_KpiEventType) String() string {
	return proto.EnumName(KpiEventType_KpiEventType_name, int32(x))
}

func (KpiEventType_KpiEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{2, 0}
}

type AlarmEventType_AlarmEventType int32

const (
	AlarmEventType_COMMUNICATION AlarmEventType_AlarmEventType = 0
	AlarmEventType_ENVIRONMENT   AlarmEventType_AlarmEventType = 1
	AlarmEventType_EQUIPMENT     AlarmEventType_AlarmEventType = 2
	AlarmEventType_SERVICE       AlarmEventType_AlarmEventType = 3
	AlarmEventType_PROCESSING    AlarmEventType_AlarmEventType = 4
	AlarmEventType_SECURITY      AlarmEventType_AlarmEventType = 5
)

var AlarmEventType_AlarmEventType_name = map[int32]string{
	0: "COMMUNICATION",
	1: "ENVIRONMENT",
	2: "EQUIPMENT",
	3: "SERVICE",
	4: "PROCESSING",
	5: "SECURITY",
}

var AlarmEventType_AlarmEventType_value = map[string]int32{
	"COMMUNICATION": 0,
	"ENVIRONMENT":   1,
	"EQUIPMENT":     2,
	"SERVICE":       3,
	"PROCESSING":    4,
	"SECURITY":      5,
}

func (x AlarmEventType_AlarmEventType) String() string {
	return proto.EnumName(AlarmEventType_AlarmEventType_name, int32(x))
}

func (AlarmEventType_AlarmEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{8, 0}
}

type AlarmEventCategory_AlarmEventCategory int32

const (
	AlarmEventCategory_PON AlarmEventCategory_AlarmEventCategory = 0
	AlarmEventCategory_OLT AlarmEventCategory_AlarmEventCategory = 1
	AlarmEventCategory_ONT AlarmEventCategory_AlarmEventCategory = 2
	AlarmEventCategory_ONU AlarmEventCategory_AlarmEventCategory = 3
	AlarmEventCategory_NNI AlarmEventCategory_AlarmEventCategory = 4
)

var AlarmEventCategory_AlarmEventCategory_name = map[int32]string{
	0: "PON",
	1: "OLT",
	2: "ONT",
	3: "ONU",
	4: "NNI",
}

var AlarmEventCategory_AlarmEventCategory_value = map[string]int32{
	"PON": 0,
	"OLT": 1,
	"ONT": 2,
	"ONU": 3,
	"NNI": 4,
}

func (x AlarmEventCategory_AlarmEventCategory) String() string {
	return proto.EnumName(AlarmEventCategory_AlarmEventCategory_name, int32(x))
}

func (AlarmEventCategory_AlarmEventCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{9, 0}
}

type AlarmEventState_AlarmEventState int32

const (
	AlarmEventState_RAISED  AlarmEventState_AlarmEventState = 0
	AlarmEventState_CLEARED AlarmEventState_AlarmEventState = 1
)

var AlarmEventState_AlarmEventState_name = map[int32]string{
	0: "RAISED",
	1: "CLEARED",
}

var AlarmEventState_AlarmEventState_value = map[string]int32{
	"RAISED":  0,
	"CLEARED": 1,
}

func (x AlarmEventState_AlarmEventState) String() string {
	return proto.EnumName(AlarmEventState_AlarmEventState_name, int32(x))
}

func (AlarmEventState_AlarmEventState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{10, 0}
}

type AlarmEventSeverity_AlarmEventSeverity int32

const (
	AlarmEventSeverity_INDETERMINATE AlarmEventSeverity_AlarmEventSeverity = 0
	AlarmEventSeverity_WARNING       AlarmEventSeverity_AlarmEventSeverity = 1
	AlarmEventSeverity_MINOR         AlarmEventSeverity_AlarmEventSeverity = 2
	AlarmEventSeverity_MAJOR         AlarmEventSeverity_AlarmEventSeverity = 3
	AlarmEventSeverity_CRITICAL      AlarmEventSeverity_AlarmEventSeverity = 4
)

var AlarmEventSeverity_AlarmEventSeverity_name = map[int32]string{
	0: "INDETERMINATE",
	1: "WARNING",
	2: "MINOR",
	3: "MAJOR",
	4: "CRITICAL",
}

var AlarmEventSeverity_AlarmEventSeverity_value = map[string]int32{
	"INDETERMINATE": 0,
	"WARNING":       1,
	"MINOR":         2,
	"MAJOR":         3,
	"CRITICAL":      4,
}

func (x AlarmEventSeverity_AlarmEventSeverity) String() string {
	return proto.EnumName(AlarmEventSeverity_AlarmEventSeverity_name, int32(x))
}

func (AlarmEventSeverity_AlarmEventSeverity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{11, 0}
}

type ConfigEventType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigEventType) Reset()         { *m = ConfigEventType{} }
func (m *ConfigEventType) String() string { return proto.CompactTextString(m) }
func (*ConfigEventType) ProtoMessage()    {}
func (*ConfigEventType) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{0}
}

func (m *ConfigEventType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigEventType.Unmarshal(m, b)
}
func (m *ConfigEventType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigEventType.Marshal(b, m, deterministic)
}
func (m *ConfigEventType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigEventType.Merge(m, src)
}
func (m *ConfigEventType) XXX_Size() int {
	return xxx_messageInfo_ConfigEventType.Size(m)
}
func (m *ConfigEventType) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigEventType.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigEventType proto.InternalMessageInfo

type ConfigEvent struct {
	Type                 ConfigEventType_ConfigEventType `protobuf:"varint,1,opt,name=type,proto3,enum=voltha.ConfigEventType_ConfigEventType" json:"type,omitempty"`
	Hash                 string                          `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Data                 string                          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ConfigEvent) Reset()         { *m = ConfigEvent{} }
func (m *ConfigEvent) String() string { return proto.CompactTextString(m) }
func (*ConfigEvent) ProtoMessage()    {}
func (*ConfigEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{1}
}

func (m *ConfigEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigEvent.Unmarshal(m, b)
}
func (m *ConfigEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigEvent.Marshal(b, m, deterministic)
}
func (m *ConfigEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigEvent.Merge(m, src)
}
func (m *ConfigEvent) XXX_Size() int {
	return xxx_messageInfo_ConfigEvent.Size(m)
}
func (m *ConfigEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigEvent proto.InternalMessageInfo

func (m *ConfigEvent) GetType() ConfigEventType_ConfigEventType {
	if m != nil {
		return m.Type
	}
	return ConfigEventType_add
}

func (m *ConfigEvent) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ConfigEvent) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type KpiEventType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KpiEventType) Reset()         { *m = KpiEventType{} }
func (m *KpiEventType) String() string { return proto.CompactTextString(m) }
func (*KpiEventType) ProtoMessage()    {}
func (*KpiEventType) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{2}
}

func (m *KpiEventType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KpiEventType.Unmarshal(m, b)
}
func (m *KpiEventType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KpiEventType.Marshal(b, m, deterministic)
}
func (m *KpiEventType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KpiEventType.Merge(m, src)
}
func (m *KpiEventType) XXX_Size() int {
	return xxx_messageInfo_KpiEventType.Size(m)
}
func (m *KpiEventType) XXX_DiscardUnknown() {
	xxx_messageInfo_KpiEventType.DiscardUnknown(m)
}

var xxx_messageInfo_KpiEventType proto.InternalMessageInfo

//
// Struct to convey a dictionary of metric metadata.
type MetricMetaData struct {
	Title           string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Ts              float64 `protobuf:"fixed64,2,opt,name=ts,proto3" json:"ts,omitempty"`
	LogicalDeviceId string  `protobuf:"bytes,3,opt,name=logical_device_id,json=logicalDeviceId,proto3" json:"logical_device_id,omitempty"`
	// (equivalent to the DPID that ONOS has
	// for the VOLTHA device without the
	//  'of:' prefix
	SerialNo             string            `protobuf:"bytes,4,opt,name=serial_no,json=serialNo,proto3" json:"serial_no,omitempty"`
	DeviceId             string            `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Context              map[string]string `protobuf:"bytes,6,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MetricMetaData) Reset()         { *m = MetricMetaData{} }
func (m *MetricMetaData) String() string { return proto.CompactTextString(m) }
func (*MetricMetaData) ProtoMessage()    {}
func (*MetricMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{3}
}

func (m *MetricMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricMetaData.Unmarshal(m, b)
}
func (m *MetricMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricMetaData.Marshal(b, m, deterministic)
}
func (m *MetricMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricMetaData.Merge(m, src)
}
func (m *MetricMetaData) XXX_Size() int {
	return xxx_messageInfo_MetricMetaData.Size(m)
}
func (m *MetricMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MetricMetaData proto.InternalMessageInfo

func (m *MetricMetaData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MetricMetaData) GetTs() float64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *MetricMetaData) GetLogicalDeviceId() string {
	if m != nil {
		return m.LogicalDeviceId
	}
	return ""
}

func (m *MetricMetaData) GetSerialNo() string {
	if m != nil {
		return m.SerialNo
	}
	return ""
}

func (m *MetricMetaData) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *MetricMetaData) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

//
// Struct to convey a dictionary of metric->value pairs. Typically used in
// pure shared-timestamp or shared-timestamp + shared object prefix situations.
type MetricValuePairs struct {
	// Metric / value pairs.
	Metrics              map[string]float32 `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MetricValuePairs) Reset()         { *m = MetricValuePairs{} }
func (m *MetricValuePairs) String() string { return proto.CompactTextString(m) }
func (*MetricValuePairs) ProtoMessage()    {}
func (*MetricValuePairs) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{4}
}

func (m *MetricValuePairs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricValuePairs.Unmarshal(m, b)
}
func (m *MetricValuePairs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricValuePairs.Marshal(b, m, deterministic)
}
func (m *MetricValuePairs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricValuePairs.Merge(m, src)
}
func (m *MetricValuePairs) XXX_Size() int {
	return xxx_messageInfo_MetricValuePairs.Size(m)
}
func (m *MetricValuePairs) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricValuePairs.DiscardUnknown(m)
}

var xxx_messageInfo_MetricValuePairs proto.InternalMessageInfo

func (m *MetricValuePairs) GetMetrics() map[string]float32 {
	if m != nil {
		return m.Metrics
	}
	return nil
}

//
// Struct to group metadata for a metric (or group of metrics) with the key-value
// pairs of collected metrics
type MetricInformation struct {
	Metadata             *MetricMetaData    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Metrics              map[string]float32 `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MetricInformation) Reset()         { *m = MetricInformation{} }
func (m *MetricInformation) String() string { return proto.CompactTextString(m) }
func (*MetricInformation) ProtoMessage()    {}
func (*MetricInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{5}
}

func (m *MetricInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricInformation.Unmarshal(m, b)
}
func (m *MetricInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricInformation.Marshal(b, m, deterministic)
}
func (m *MetricInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricInformation.Merge(m, src)
}
func (m *MetricInformation) XXX_Size() int {
	return xxx_messageInfo_MetricInformation.Size(m)
}
func (m *MetricInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricInformation.DiscardUnknown(m)
}

var xxx_messageInfo_MetricInformation proto.InternalMessageInfo

func (m *MetricInformation) GetMetadata() *MetricMetaData {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MetricInformation) GetMetrics() map[string]float32 {
	if m != nil {
		return m.Metrics
	}
	return nil
}

//
// Legacy KPI Event structured.  In mid-August, the KPI event format was updated
//                               to a more easily parsable format. See VOL-1140
//                               for more information.
type KpiEvent struct {
	Type                 KpiEventType_KpiEventType    `protobuf:"varint,1,opt,name=type,proto3,enum=voltha.KpiEventType_KpiEventType" json:"type,omitempty"`
	Ts                   float32                      `protobuf:"fixed32,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Prefixes             map[string]*MetricValuePairs `protobuf:"bytes,3,rep,name=prefixes,proto3" json:"prefixes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *KpiEvent) Reset()         { *m = KpiEvent{} }
func (m *KpiEvent) String() string { return proto.CompactTextString(m) }
func (*KpiEvent) ProtoMessage()    {}
func (*KpiEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{6}
}

func (m *KpiEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KpiEvent.Unmarshal(m, b)
}
func (m *KpiEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KpiEvent.Marshal(b, m, deterministic)
}
func (m *KpiEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KpiEvent.Merge(m, src)
}
func (m *KpiEvent) XXX_Size() int {
	return xxx_messageInfo_KpiEvent.Size(m)
}
func (m *KpiEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_KpiEvent.DiscardUnknown(m)
}

var xxx_messageInfo_KpiEvent proto.InternalMessageInfo

func (m *KpiEvent) GetType() KpiEventType_KpiEventType {
	if m != nil {
		return m.Type
	}
	return KpiEventType_slice
}

func (m *KpiEvent) GetTs() float32 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *KpiEvent) GetPrefixes() map[string]*MetricValuePairs {
	if m != nil {
		return m.Prefixes
	}
	return nil
}

type KpiEvent2 struct {
	// Type of KPI Event
	Type KpiEventType_KpiEventType `protobuf:"varint,1,opt,name=type,proto3,enum=voltha.KpiEventType_KpiEventType" json:"type,omitempty"`
	// Fields used when for slice:
	Ts                   float64              `protobuf:"fixed64,2,opt,name=ts,proto3" json:"ts,omitempty"`
	SliceData            []*MetricInformation `protobuf:"bytes,3,rep,name=slice_data,json=sliceData,proto3" json:"slice_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *KpiEvent2) Reset()         { *m = KpiEvent2{} }
func (m *KpiEvent2) String() string { return proto.CompactTextString(m) }
func (*KpiEvent2) ProtoMessage()    {}
func (*KpiEvent2) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{7}
}

func (m *KpiEvent2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KpiEvent2.Unmarshal(m, b)
}
func (m *KpiEvent2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KpiEvent2.Marshal(b, m, deterministic)
}
func (m *KpiEvent2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KpiEvent2.Merge(m, src)
}
func (m *KpiEvent2) XXX_Size() int {
	return xxx_messageInfo_KpiEvent2.Size(m)
}
func (m *KpiEvent2) XXX_DiscardUnknown() {
	xxx_messageInfo_KpiEvent2.DiscardUnknown(m)
}

var xxx_messageInfo_KpiEvent2 proto.InternalMessageInfo

func (m *KpiEvent2) GetType() KpiEventType_KpiEventType {
	if m != nil {
		return m.Type
	}
	return KpiEventType_slice
}

func (m *KpiEvent2) GetTs() float64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *KpiEvent2) GetSliceData() []*MetricInformation {
	if m != nil {
		return m.SliceData
	}
	return nil
}

//
// Identify to the area of the system impacted by the alarm
type AlarmEventType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmEventType) Reset()         { *m = AlarmEventType{} }
func (m *AlarmEventType) String() string { return proto.CompactTextString(m) }
func (*AlarmEventType) ProtoMessage()    {}
func (*AlarmEventType) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{8}
}

func (m *AlarmEventType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmEventType.Unmarshal(m, b)
}
func (m *AlarmEventType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmEventType.Marshal(b, m, deterministic)
}
func (m *AlarmEventType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmEventType.Merge(m, src)
}
func (m *AlarmEventType) XXX_Size() int {
	return xxx_messageInfo_AlarmEventType.Size(m)
}
func (m *AlarmEventType) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmEventType.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmEventType proto.InternalMessageInfo

//
// Identify to the functional category originating the alarm
type AlarmEventCategory struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmEventCategory) Reset()         { *m = AlarmEventCategory{} }
func (m *AlarmEventCategory) String() string { return proto.CompactTextString(m) }
func (*AlarmEventCategory) ProtoMessage()    {}
func (*AlarmEventCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{9}
}

func (m *AlarmEventCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmEventCategory.Unmarshal(m, b)
}
func (m *AlarmEventCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmEventCategory.Marshal(b, m, deterministic)
}
func (m *AlarmEventCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmEventCategory.Merge(m, src)
}
func (m *AlarmEventCategory) XXX_Size() int {
	return xxx_messageInfo_AlarmEventCategory.Size(m)
}
func (m *AlarmEventCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmEventCategory.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmEventCategory proto.InternalMessageInfo

//
// Active state of the alarm
type AlarmEventState struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmEventState) Reset()         { *m = AlarmEventState{} }
func (m *AlarmEventState) String() string { return proto.CompactTextString(m) }
func (*AlarmEventState) ProtoMessage()    {}
func (*AlarmEventState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{10}
}

func (m *AlarmEventState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmEventState.Unmarshal(m, b)
}
func (m *AlarmEventState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmEventState.Marshal(b, m, deterministic)
}
func (m *AlarmEventState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmEventState.Merge(m, src)
}
func (m *AlarmEventState) XXX_Size() int {
	return xxx_messageInfo_AlarmEventState.Size(m)
}
func (m *AlarmEventState) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmEventState.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmEventState proto.InternalMessageInfo

//
// Identify the overall impact of the alarm on the system
type AlarmEventSeverity struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmEventSeverity) Reset()         { *m = AlarmEventSeverity{} }
func (m *AlarmEventSeverity) String() string { return proto.CompactTextString(m) }
func (*AlarmEventSeverity) ProtoMessage()    {}
func (*AlarmEventSeverity) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{11}
}

func (m *AlarmEventSeverity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmEventSeverity.Unmarshal(m, b)
}
func (m *AlarmEventSeverity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmEventSeverity.Marshal(b, m, deterministic)
}
func (m *AlarmEventSeverity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmEventSeverity.Merge(m, src)
}
func (m *AlarmEventSeverity) XXX_Size() int {
	return xxx_messageInfo_AlarmEventSeverity.Size(m)
}
func (m *AlarmEventSeverity) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmEventSeverity.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmEventSeverity proto.InternalMessageInfo

//
//
type AlarmEvent struct {
	// Unique ID for this alarm.  e.g. voltha.some_olt.1234
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Refers to the area of the system impacted by the alarm
	Type AlarmEventType_AlarmEventType `protobuf:"varint,2,opt,name=type,proto3,enum=voltha.AlarmEventType_AlarmEventType" json:"type,omitempty"`
	// Refers to functional category of the alarm
	Category AlarmEventCategory_AlarmEventCategory `protobuf:"varint,3,opt,name=category,proto3,enum=voltha.AlarmEventCategory_AlarmEventCategory" json:"category,omitempty"`
	// Current active state of the alarm
	State AlarmEventState_AlarmEventState `protobuf:"varint,4,opt,name=state,proto3,enum=voltha.AlarmEventState_AlarmEventState" json:"state,omitempty"`
	// Overall impact of the alarm on the system
	Severity AlarmEventSeverity_AlarmEventSeverity `protobuf:"varint,5,opt,name=severity,proto3,enum=voltha.AlarmEventSeverity_AlarmEventSeverity" json:"severity,omitempty"`
	// Timestamp at which the alarm was first raised
	RaisedTs float32 `protobuf:"fixed32,6,opt,name=raised_ts,json=raisedTs,proto3" json:"raised_ts,omitempty"`
	// Timestamp at which the alarm was reported
	ReportedTs float32 `protobuf:"fixed32,7,opt,name=reported_ts,json=reportedTs,proto3" json:"reported_ts,omitempty"`
	// Timestamp at which the alarm has changed since it was raised
	ChangedTs float32 `protobuf:"fixed32,8,opt,name=changed_ts,json=changedTs,proto3" json:"changed_ts,omitempty"`
	// Identifier of the originating resource of the alarm
	ResourceId string `protobuf:"bytes,9,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// Textual explanation of the alarm
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// Key/Value storage for extra information that may give context to the alarm
	Context map[string]string `protobuf:"bytes,11,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// logical device id
	LogicalDeviceId string `protobuf:"bytes,12,opt,name=logical_device_id,json=logicalDeviceId,proto3" json:"logical_device_id,omitempty"`
	// alarm_type  name indicates clearly the name of the alarm
	AlarmTypeName        string   `protobuf:"bytes,13,opt,name=alarm_type_name,json=alarmTypeName,proto3" json:"alarm_type_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmEvent) Reset()         { *m = AlarmEvent{} }
func (m *AlarmEvent) String() string { return proto.CompactTextString(m) }
func (*AlarmEvent) ProtoMessage()    {}
func (*AlarmEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63e6c07044fd2c4, []int{12}
}

func (m *AlarmEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmEvent.Unmarshal(m, b)
}
func (m *AlarmEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmEvent.Marshal(b, m, deterministic)
}
func (m *AlarmEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmEvent.Merge(m, src)
}
func (m *AlarmEvent) XXX_Size() int {
	return xxx_messageInfo_AlarmEvent.Size(m)
}
func (m *AlarmEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmEvent proto.InternalMessageInfo

func (m *AlarmEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AlarmEvent) GetType() AlarmEventType_AlarmEventType {
	if m != nil {
		return m.Type
	}
	return AlarmEventType_COMMUNICATION
}

func (m *AlarmEvent) GetCategory() AlarmEventCategory_AlarmEventCategory {
	if m != nil {
		return m.Category
	}
	return AlarmEventCategory_PON
}

func (m *AlarmEvent) GetState() AlarmEventState_AlarmEventState {
	if m != nil {
		return m.State
	}
	return AlarmEventState_RAISED
}

func (m *AlarmEvent) GetSeverity() AlarmEventSeverity_AlarmEventSeverity {
	if m != nil {
		return m.Severity
	}
	return AlarmEventSeverity_INDETERMINATE
}

func (m *AlarmEvent) GetRaisedTs() float32 {
	if m != nil {
		return m.RaisedTs
	}
	return 0
}

func (m *AlarmEvent) GetReportedTs() float32 {
	if m != nil {
		return m.ReportedTs
	}
	return 0
}

func (m *AlarmEvent) GetChangedTs() float32 {
	if m != nil {
		return m.ChangedTs
	}
	return 0
}

func (m *AlarmEvent) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *AlarmEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AlarmEvent) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *AlarmEvent) GetLogicalDeviceId() string {
	if m != nil {
		return m.LogicalDeviceId
	}
	return ""
}

func (m *AlarmEvent) GetAlarmTypeName() string {
	if m != nil {
		return m.AlarmTypeName
	}
	return ""
}

func init() {
	proto.RegisterEnum("voltha.ConfigEventType_ConfigEventType", ConfigEventType_ConfigEventType_name, ConfigEventType_ConfigEventType_value)
	proto.RegisterEnum("voltha.KpiEventType_KpiEventType", KpiEventType_KpiEventType_name, KpiEventType_KpiEventType_value)
	proto.RegisterEnum("voltha.AlarmEventType_AlarmEventType", AlarmEventType_AlarmEventType_name, AlarmEventType_AlarmEventType_value)
	proto.RegisterEnum("voltha.AlarmEventCategory_AlarmEventCategory", AlarmEventCategory_AlarmEventCategory_name, AlarmEventCategory_AlarmEventCategory_value)
	proto.RegisterEnum("voltha.AlarmEventState_AlarmEventState", AlarmEventState_AlarmEventState_name, AlarmEventState_AlarmEventState_value)
	proto.RegisterEnum("voltha.AlarmEventSeverity_AlarmEventSeverity", AlarmEventSeverity_AlarmEventSeverity_name, AlarmEventSeverity_AlarmEventSeverity_value)
	proto.RegisterType((*ConfigEventType)(nil), "voltha.ConfigEventType")
	proto.RegisterType((*ConfigEvent)(nil), "voltha.ConfigEvent")
	proto.RegisterType((*KpiEventType)(nil), "voltha.KpiEventType")
	proto.RegisterType((*MetricMetaData)(nil), "voltha.MetricMetaData")
	proto.RegisterMapType((map[string]string)(nil), "voltha.MetricMetaData.ContextEntry")
	proto.RegisterType((*MetricValuePairs)(nil), "voltha.MetricValuePairs")
	proto.RegisterMapType((map[string]float32)(nil), "voltha.MetricValuePairs.MetricsEntry")
	proto.RegisterType((*MetricInformation)(nil), "voltha.MetricInformation")
	proto.RegisterMapType((map[string]float32)(nil), "voltha.MetricInformation.MetricsEntry")
	proto.RegisterType((*KpiEvent)(nil), "voltha.KpiEvent")
	proto.RegisterMapType((map[string]*MetricValuePairs)(nil), "voltha.KpiEvent.PrefixesEntry")
	proto.RegisterType((*KpiEvent2)(nil), "voltha.KpiEvent2")
	proto.RegisterType((*AlarmEventType)(nil), "voltha.AlarmEventType")
	proto.RegisterType((*AlarmEventCategory)(nil), "voltha.AlarmEventCategory")
	proto.RegisterType((*AlarmEventState)(nil), "voltha.AlarmEventState")
	proto.RegisterType((*AlarmEventSeverity)(nil), "voltha.AlarmEventSeverity")
	proto.RegisterType((*AlarmEvent)(nil), "voltha.AlarmEvent")
	proto.RegisterMapType((map[string]string)(nil), "voltha.AlarmEvent.ContextEntry")
}

func init() { proto.RegisterFile("voltha_protos/events.proto", fileDescriptor_e63e6c07044fd2c4) }

var fileDescriptor_e63e6c07044fd2c4 = []byte{
	// 1040 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x9d, 0xff, 0x93, 0x36, 0xf5, 0x8e, 0x10, 0x32, 0xe5, 0x67, 0xbb, 0x46, 0x2c, 0xd5,
	0x4a, 0x4d, 0xb4, 0x01, 0xa4, 0xdd, 0xa2, 0x0a, 0x82, 0x6b, 0x21, 0x43, 0xe3, 0x94, 0x49, 0xda,
	0x05, 0x6e, 0xa2, 0x69, 0x3c, 0x4d, 0x47, 0x9b, 0xd8, 0x96, 0x3d, 0x8d, 0x36, 0x77, 0x3c, 0x00,
	0x12, 0x97, 0xfb, 0x44, 0xbc, 0x09, 0x0f, 0x82, 0x66, 0xc6, 0xae, 0x9d, 0xd4, 0x2b, 0x2e, 0x56,
	0xdc, 0xcd, 0xf9, 0xce, 0x8f, 0xbf, 0x73, 0xe6, 0xcc, 0x39, 0x86, 0x83, 0x55, 0xb8, 0xe0, 0xb7,
	0x64, 0x1a, 0xc5, 0x21, 0x0f, 0x93, 0x1e, 0x5d, 0xd1, 0x80, 0x27, 0x5d, 0x29, 0xa1, 0xba, 0xd2,
	0x1d, 0x98, 0x9b, 0x36, 0x4b, 0xca, 0x89, 0xb2, 0x38, 0xf8, 0x64, 0x1e, 0x86, 0xf3, 0x05, 0xed,
	0x91, 0x88, 0xf5, 0x48, 0x10, 0x84, 0x9c, 0x70, 0x16, 0x06, 0xa9, 0xbf, 0xe5, 0xc0, 0xbe, 0x1d,
	0x06, 0x37, 0x6c, 0xee, 0x88, 0xa8, 0x93, 0x75, 0x44, 0xad, 0xfe, 0x03, 0x08, 0x35, 0xa0, 0x42,
	0x7c, 0xdf, 0xd8, 0x41, 0x00, 0xf5, 0x98, 0x2e, 0xc3, 0x15, 0x35, 0x34, 0x71, 0xbe, 0x8b, 0x7c,
	0xc2, 0xa9, 0xa1, 0x5b, 0x31, 0xb4, 0x0b, 0x3e, 0xe8, 0x5b, 0xa8, 0xf2, 0x75, 0x44, 0x4d, 0xed,
	0x50, 0x3b, 0xea, 0xf4, 0xbf, 0xec, 0x2a, 0x72, 0xdd, 0xad, 0xb0, 0xdb, 0x32, 0x96, 0x4e, 0x08,
	0x41, 0xf5, 0x96, 0x24, 0xb7, 0xa6, 0x7e, 0xa8, 0x1d, 0xb5, 0xb0, 0x3c, 0x0b, 0xcc, 0x27, 0x9c,
	0x98, 0x15, 0x85, 0x89, 0xb3, 0xf5, 0x1c, 0x76, 0x7f, 0x8e, 0x58, 0xce, 0xfb, 0xc9, 0xa6, 0x8c,
	0x5a, 0x50, 0x4b, 0x16, 0x6c, 0x46, 0x8d, 0x1d, 0x54, 0x07, 0x9d, 0x27, 0x86, 0x66, 0xbd, 0xd5,
	0xa1, 0x33, 0xa4, 0x3c, 0x66, 0xb3, 0x21, 0xe5, 0xe4, 0x8c, 0x70, 0x82, 0x3e, 0x80, 0x1a, 0x67,
	0x7c, 0xa1, 0xb8, 0xb6, 0xb0, 0x12, 0x50, 0x47, 0x38, 0x48, 0x06, 0x1a, 0xd6, 0x79, 0x82, 0x9e,
	0xc1, 0xa3, 0x45, 0x38, 0x67, 0x33, 0xb2, 0x98, 0xfa, 0x74, 0xc5, 0x66, 0x74, 0xca, 0xfc, 0x94,
	0xcc, 0x7e, 0xaa, 0x38, 0x93, 0xb8, 0xeb, 0xa3, 0x8f, 0xa1, 0x95, 0xd0, 0x98, 0x91, 0xc5, 0x34,
	0x08, 0xcd, 0xaa, 0xb4, 0x69, 0x2a, 0xc0, 0x0b, 0x85, 0x32, 0x0f, 0x50, 0x53, 0x4a, 0x3f, 0xf3,
	0x3c, 0x85, 0xc6, 0x2c, 0x0c, 0x38, 0x7d, 0xc3, 0xcd, 0xfa, 0x61, 0xe5, 0xa8, 0xdd, 0xff, 0x3c,
	0xab, 0xdc, 0x26, 0x69, 0x51, 0x38, 0x61, 0xe5, 0x04, 0x3c, 0x5e, 0xe3, 0xcc, 0xe7, 0xe0, 0x04,
	0x76, 0x8b, 0x0a, 0x64, 0x40, 0xe5, 0x35, 0x5d, 0xa7, 0x89, 0x89, 0xa3, 0x48, 0x76, 0x45, 0x16,
	0x77, 0x34, 0xad, 0xad, 0x12, 0x4e, 0xf4, 0x17, 0x9a, 0xf5, 0x97, 0x06, 0x86, 0xfa, 0xc8, 0x95,
	0xc0, 0x2e, 0x08, 0x8b, 0x13, 0xf4, 0x1d, 0x34, 0x96, 0x12, 0x4b, 0x4c, 0x4d, 0xf2, 0xf9, 0x62,
	0x93, 0x4f, 0x6e, 0x9a, 0x02, 0x49, 0xca, 0x28, 0xf5, 0x12, 0x8c, 0x8a, 0x8a, 0xff, 0x62, 0xa4,
	0x17, 0x19, 0xfd, 0xad, 0xc1, 0x23, 0xe5, 0xec, 0x06, 0x37, 0x61, 0xbc, 0x94, 0x6d, 0x8b, 0xfa,
	0xd0, 0x14, 0xbd, 0x2d, 0x9b, 0x41, 0x84, 0x69, 0xf7, 0x3f, 0x2c, 0xaf, 0x11, 0xbe, 0xb7, 0x43,
	0xdf, 0xe7, 0x69, 0xe8, 0x32, 0x8d, 0xa7, 0x9b, 0x2e, 0x85, 0xf8, 0xff, 0x43, 0x1e, 0xff, 0x68,
	0xd0, 0xcc, 0xfa, 0x12, 0x7d, 0xb3, 0xf1, 0x30, 0x9e, 0x64, 0x3c, 0x8a, 0x7d, 0xbb, 0x21, 0xa4,
	0x4f, 0x22, 0x6f, 0x47, 0x5d, 0xb6, 0xe3, 0x09, 0x34, 0xa3, 0x98, 0xde, 0xb0, 0x37, 0x34, 0x31,
	0x2b, 0x32, 0xa5, 0xcf, 0xb6, 0x43, 0x75, 0x2f, 0x52, 0x03, 0x95, 0xca, 0xbd, 0xfd, 0xc1, 0x25,
	0xec, 0x6d, 0xa8, 0x4a, 0x92, 0xe9, 0x16, 0x93, 0x69, 0xf7, 0xcd, 0x77, 0xdd, 0x7a, 0x31, 0xcd,
	0x3f, 0x35, 0x68, 0x65, 0xdf, 0xee, 0xbf, 0x7f, 0x9e, 0xea, 0xd9, 0xbd, 0x00, 0x90, 0x4f, 0x78,
	0x9a, 0x3e, 0x7e, 0x91, 0xe9, 0x47, 0xef, 0xbc, 0x3c, 0xdc, 0x92, 0xc6, 0xe2, 0xf6, 0xad, 0x3f,
	0x34, 0xe8, 0x0c, 0x16, 0x24, 0x5e, 0xe6, 0xf3, 0x21, 0xd8, 0x46, 0xd0, 0x23, 0xd8, 0xb3, 0x47,
	0xc3, 0xe1, 0xa5, 0xe7, 0xda, 0x83, 0x89, 0x3b, 0xf2, 0x8c, 0x1d, 0xb4, 0x0f, 0x6d, 0xc7, 0xbb,
	0x72, 0xf1, 0xc8, 0x1b, 0x3a, 0xde, 0xc4, 0xd0, 0xd0, 0x1e, 0xb4, 0x9c, 0x5f, 0x2e, 0xdd, 0x0b,
	0x29, 0xea, 0xa8, 0x0d, 0x8d, 0xb1, 0x83, 0xaf, 0x5c, 0xdb, 0x31, 0x2a, 0xa8, 0x03, 0x70, 0x81,
	0x47, 0xb6, 0x33, 0x1e, 0xbb, 0xde, 0x8f, 0x46, 0x15, 0xed, 0x42, 0x73, 0xec, 0xd8, 0x97, 0xd8,
	0x9d, 0xfc, 0x66, 0xd4, 0xac, 0x57, 0x80, 0xf2, 0xef, 0xd9, 0x84, 0xd3, 0x79, 0x18, 0xaf, 0xad,
	0x41, 0x19, 0x2a, 0x06, 0xec, 0x85, 0xfc, 0x7e, 0x03, 0x2a, 0xa3, 0x73, 0xf1, 0x5d, 0x71, 0x90,
	0x5f, 0x94, 0x87, 0x4b, 0xa3, 0x22, 0x0e, 0x9e, 0xe7, 0x1a, 0x55, 0xeb, 0x14, 0xf6, 0xf3, 0x10,
	0x63, 0x4e, 0x38, 0xb5, 0x9e, 0x3d, 0x80, 0xc4, 0x78, 0xc6, 0x03, 0x77, 0xec, 0x9c, 0x19, 0x3b,
	0x82, 0xb5, 0x7d, 0xee, 0x0c, 0xb0, 0x73, 0x66, 0x68, 0x56, 0x50, 0x64, 0x30, 0xa6, 0x2b, 0x1a,
	0x33, 0xbe, 0xb6, 0x7e, 0x2d, 0x43, 0x45, 0x85, 0x5c, 0xef, 0xcc, 0x99, 0x38, 0x78, 0xe8, 0x7a,
	0x83, 0x89, 0xa3, 0x62, 0xbd, 0x1a, 0x60, 0x4f, 0x64, 0xac, 0x89, 0x19, 0x3b, 0x74, 0xbd, 0x11,
	0x36, 0x74, 0x79, 0x1c, 0xfc, 0x34, 0xc2, 0x46, 0x45, 0xd4, 0xc1, 0xc6, 0xee, 0xc4, 0xb5, 0x07,
	0xe7, 0x46, 0xd5, 0x7a, 0x5b, 0x03, 0xc8, 0x43, 0x8b, 0x3b, 0x66, 0x7e, 0xda, 0x6d, 0x3a, 0xf3,
	0xd1, 0xcb, 0xb4, 0x55, 0x74, 0xd9, 0x2a, 0xf7, 0x13, 0x66, 0xf3, 0xaa, 0xb6, 0xc4, 0xb4, 0x5d,
	0x5c, 0x68, 0xce, 0xd2, 0x0a, 0xca, 0x61, 0xdc, 0xe9, 0x1f, 0x3f, 0x74, 0xcf, 0x6a, 0x5c, 0x02,
	0xe1, 0x7b, 0x77, 0x74, 0x0a, 0xb5, 0x44, 0x94, 0x4d, 0x0e, 0xec, 0xc2, 0xca, 0xda, 0xaa, 0xea,
	0xb6, 0x8c, 0x95, 0x97, 0x60, 0x92, 0xa4, 0x35, 0x93, 0x53, 0xbd, 0x94, 0x49, 0x56, 0xd5, 0x12,
	0x08, 0xdf, 0xbb, 0x8b, 0x0d, 0x11, 0x13, 0x96, 0x50, 0x7f, 0xca, 0x13, 0xb3, 0x2e, 0x9f, 0x7c,
	0x53, 0x01, 0x93, 0x04, 0x3d, 0x86, 0x76, 0x4c, 0xa3, 0x30, 0xe6, 0x4a, 0xdd, 0x90, 0x6a, 0xc8,
	0xa0, 0x49, 0x82, 0x3e, 0x05, 0x98, 0xdd, 0x92, 0x60, 0xae, 0xf4, 0x4d, 0xa9, 0x6f, 0xa5, 0x48,
	0xe6, 0x9f, 0x84, 0x77, 0xb1, 0x5a, 0x40, 0x2d, 0x79, 0x0b, 0x90, 0x41, 0xae, 0x8f, 0x0e, 0xa1,
	0xed, 0xd3, 0x64, 0x16, 0xb3, 0x48, 0xbc, 0x28, 0x13, 0xa4, 0x41, 0x11, 0x42, 0x2f, 0xf3, 0x25,
	0xd5, 0x96, 0x0f, 0xf2, 0xf1, 0xc3, 0x4c, 0xcb, 0x17, 0x54, 0xf9, 0x16, 0xdd, 0x2d, 0xdf, 0xa2,
	0x4f, 0x61, 0x9f, 0x88, 0x78, 0x53, 0x71, 0xd3, 0xd3, 0x80, 0x2c, 0xa9, 0xb9, 0x27, 0x2d, 0xf7,
	0x24, 0x2c, 0xba, 0xc0, 0x23, 0x4b, 0xfa, 0x3e, 0x4b, 0xef, 0x87, 0xaf, 0x7f, 0xef, 0xcf, 0xc3,
	0xe8, 0xf5, 0xbc, 0xcb, 0x82, 0x9e, 0x7f, 0x4d, 0x58, 0x70, 0x1d, 0xb3, 0xe3, 0x19, 0xa3, 0x01,
	0xe9, 0xa9, 0x94, 0x8e, 0xd5, 0xef, 0x54, 0x77, 0xf5, 0xbc, 0x37, 0x0f, 0x53, 0xec, 0xba, 0x2e,
	0xc1, 0xaf, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xc5, 0xef, 0x01, 0x97, 0x09, 0x00, 0x00,
}
