// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/logical_device.proto

package voltha

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "gopkg.in/dbainbri-ciena/voltha-protos.v1/go/common"
	openflow_13 "gopkg.in/dbainbri-ciena/voltha-protos.v1/go/openflow_13"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogicalPortId struct {
	// unique id of logical device
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// id of the port on the logical device
	PortId               string   `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogicalPortId) Reset()         { *m = LogicalPortId{} }
func (m *LogicalPortId) String() string { return proto.CompactTextString(m) }
func (*LogicalPortId) ProtoMessage()    {}
func (*LogicalPortId) Descriptor() ([]byte, []int) {
	return fileDescriptor_caf139ab3abc8240, []int{0}
}

func (m *LogicalPortId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogicalPortId.Unmarshal(m, b)
}
func (m *LogicalPortId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogicalPortId.Marshal(b, m, deterministic)
}
func (m *LogicalPortId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalPortId.Merge(m, src)
}
func (m *LogicalPortId) XXX_Size() int {
	return xxx_messageInfo_LogicalPortId.Size(m)
}
func (m *LogicalPortId) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalPortId.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalPortId proto.InternalMessageInfo

func (m *LogicalPortId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LogicalPortId) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

type LogicalPort struct {
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OfpPort              *openflow_13.OfpPort      `protobuf:"bytes,2,opt,name=ofp_port,json=ofpPort,proto3" json:"ofp_port,omitempty"`
	DeviceId             string                    `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DevicePortNo         uint32                    `protobuf:"varint,4,opt,name=device_port_no,json=devicePortNo,proto3" json:"device_port_no,omitempty"`
	RootPort             bool                      `protobuf:"varint,5,opt,name=root_port,json=rootPort,proto3" json:"root_port,omitempty"`
	OfpPortStats         *openflow_13.OfpPortStats `protobuf:"bytes,6,opt,name=ofp_port_stats,json=ofpPortStats,proto3" json:"ofp_port_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *LogicalPort) Reset()         { *m = LogicalPort{} }
func (m *LogicalPort) String() string { return proto.CompactTextString(m) }
func (*LogicalPort) ProtoMessage()    {}
func (*LogicalPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_caf139ab3abc8240, []int{1}
}

func (m *LogicalPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogicalPort.Unmarshal(m, b)
}
func (m *LogicalPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogicalPort.Marshal(b, m, deterministic)
}
func (m *LogicalPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalPort.Merge(m, src)
}
func (m *LogicalPort) XXX_Size() int {
	return xxx_messageInfo_LogicalPort.Size(m)
}
func (m *LogicalPort) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalPort.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalPort proto.InternalMessageInfo

func (m *LogicalPort) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LogicalPort) GetOfpPort() *openflow_13.OfpPort {
	if m != nil {
		return m.OfpPort
	}
	return nil
}

func (m *LogicalPort) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *LogicalPort) GetDevicePortNo() uint32 {
	if m != nil {
		return m.DevicePortNo
	}
	return 0
}

func (m *LogicalPort) GetRootPort() bool {
	if m != nil {
		return m.RootPort
	}
	return false
}

func (m *LogicalPort) GetOfpPortStats() *openflow_13.OfpPortStats {
	if m != nil {
		return m.OfpPortStats
	}
	return nil
}

type LogicalPorts struct {
	Items                []*LogicalPort `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LogicalPorts) Reset()         { *m = LogicalPorts{} }
func (m *LogicalPorts) String() string { return proto.CompactTextString(m) }
func (*LogicalPorts) ProtoMessage()    {}
func (*LogicalPorts) Descriptor() ([]byte, []int) {
	return fileDescriptor_caf139ab3abc8240, []int{2}
}

func (m *LogicalPorts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogicalPorts.Unmarshal(m, b)
}
func (m *LogicalPorts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogicalPorts.Marshal(b, m, deterministic)
}
func (m *LogicalPorts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalPorts.Merge(m, src)
}
func (m *LogicalPorts) XXX_Size() int {
	return xxx_messageInfo_LogicalPorts.Size(m)
}
func (m *LogicalPorts) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalPorts.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalPorts proto.InternalMessageInfo

func (m *LogicalPorts) GetItems() []*LogicalPort {
	if m != nil {
		return m.Items
	}
	return nil
}

type LogicalDevice struct {
	// unique id of logical device
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// unique datapath id for the logical device (used by the SDN controller)
	DatapathId uint64 `protobuf:"varint,2,opt,name=datapath_id,json=datapathId,proto3" json:"datapath_id,omitempty"`
	// device description
	Desc *openflow_13.OfpDesc `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	// device features
	SwitchFeatures *openflow_13.OfpSwitchFeatures `protobuf:"bytes,4,opt,name=switch_features,json=switchFeatures,proto3" json:"switch_features,omitempty"`
	// name of the root device anchoring logical device
	RootDeviceId string `protobuf:"bytes,5,opt,name=root_device_id,json=rootDeviceId,proto3" json:"root_device_id,omitempty"`
	// logical device ports
	Ports []*LogicalPort `protobuf:"bytes,128,rep,name=ports,proto3" json:"ports,omitempty"`
	// flows configured on the logical device
	Flows *openflow_13.Flows `protobuf:"bytes,129,opt,name=flows,proto3" json:"flows,omitempty"`
	// meters configured on the logical device
	Meters *openflow_13.Meters `protobuf:"bytes,130,opt,name=meters,proto3" json:"meters,omitempty"`
	// flow groups configured on the logical device
	FlowGroups           *openflow_13.FlowGroups `protobuf:"bytes,131,opt,name=flow_groups,json=flowGroups,proto3" json:"flow_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LogicalDevice) Reset()         { *m = LogicalDevice{} }
func (m *LogicalDevice) String() string { return proto.CompactTextString(m) }
func (*LogicalDevice) ProtoMessage()    {}
func (*LogicalDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_caf139ab3abc8240, []int{3}
}

func (m *LogicalDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogicalDevice.Unmarshal(m, b)
}
func (m *LogicalDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogicalDevice.Marshal(b, m, deterministic)
}
func (m *LogicalDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalDevice.Merge(m, src)
}
func (m *LogicalDevice) XXX_Size() int {
	return xxx_messageInfo_LogicalDevice.Size(m)
}
func (m *LogicalDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalDevice.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalDevice proto.InternalMessageInfo

func (m *LogicalDevice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LogicalDevice) GetDatapathId() uint64 {
	if m != nil {
		return m.DatapathId
	}
	return 0
}

func (m *LogicalDevice) GetDesc() *openflow_13.OfpDesc {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *LogicalDevice) GetSwitchFeatures() *openflow_13.OfpSwitchFeatures {
	if m != nil {
		return m.SwitchFeatures
	}
	return nil
}

func (m *LogicalDevice) GetRootDeviceId() string {
	if m != nil {
		return m.RootDeviceId
	}
	return ""
}

func (m *LogicalDevice) GetPorts() []*LogicalPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *LogicalDevice) GetFlows() *openflow_13.Flows {
	if m != nil {
		return m.Flows
	}
	return nil
}

func (m *LogicalDevice) GetMeters() *openflow_13.Meters {
	if m != nil {
		return m.Meters
	}
	return nil
}

func (m *LogicalDevice) GetFlowGroups() *openflow_13.FlowGroups {
	if m != nil {
		return m.FlowGroups
	}
	return nil
}

type LogicalDevices struct {
	Items                []*LogicalDevice `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LogicalDevices) Reset()         { *m = LogicalDevices{} }
func (m *LogicalDevices) String() string { return proto.CompactTextString(m) }
func (*LogicalDevices) ProtoMessage()    {}
func (*LogicalDevices) Descriptor() ([]byte, []int) {
	return fileDescriptor_caf139ab3abc8240, []int{4}
}

func (m *LogicalDevices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogicalDevices.Unmarshal(m, b)
}
func (m *LogicalDevices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogicalDevices.Marshal(b, m, deterministic)
}
func (m *LogicalDevices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalDevices.Merge(m, src)
}
func (m *LogicalDevices) XXX_Size() int {
	return xxx_messageInfo_LogicalDevices.Size(m)
}
func (m *LogicalDevices) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalDevices.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalDevices proto.InternalMessageInfo

func (m *LogicalDevices) GetItems() []*LogicalDevice {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*LogicalPortId)(nil), "voltha.LogicalPortId")
	proto.RegisterType((*LogicalPort)(nil), "voltha.LogicalPort")
	proto.RegisterType((*LogicalPorts)(nil), "voltha.LogicalPorts")
	proto.RegisterType((*LogicalDevice)(nil), "voltha.LogicalDevice")
	proto.RegisterType((*LogicalDevices)(nil), "voltha.LogicalDevices")
}

func init() { proto.RegisterFile("voltha_protos/logical_device.proto", fileDescriptor_caf139ab3abc8240) }

var fileDescriptor_caf139ab3abc8240 = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0x5f, 0x37, 0x71, 0x9a, 0x8c, 0xd3, 0xbc, 0xd2, 0x56, 0x55, 0xad, 0x16, 0xd4, 0xc8,
	0xe2, 0x90, 0x0a, 0xd5, 0x6e, 0x13, 0x90, 0xe0, 0x80, 0x04, 0x51, 0x55, 0x14, 0x09, 0x10, 0x5a,
	0x6e, 0x5c, 0xac, 0x4d, 0xbc, 0x71, 0x56, 0x24, 0x1e, 0xcb, 0xbb, 0x4d, 0xaf, 0xfc, 0xf9, 0x5a,
	0x7c, 0x05, 0xbe, 0x04, 0x1f, 0x81, 0x03, 0x67, 0xb4, 0xbb, 0x76, 0x89, 0x9b, 0x72, 0xf4, 0x33,
	0xbf, 0x67, 0x66, 0xf6, 0x19, 0x19, 0x82, 0x35, 0x2e, 0xd5, 0x82, 0xc5, 0x79, 0x81, 0x0a, 0x65,
	0xb4, 0xc4, 0x54, 0xcc, 0xd8, 0x32, 0x4e, 0xf8, 0x5a, 0xcc, 0x78, 0x68, 0x54, 0xd2, 0xb2, 0xcc,
	0x91, 0x5f, 0x67, 0x57, 0x5c, 0x31, 0x4b, 0x1c, 0x3d, 0x48, 0x11, 0xd3, 0x25, 0x8f, 0x58, 0x2e,
	0x22, 0x96, 0x65, 0xa8, 0x98, 0x12, 0x98, 0xc9, 0xb2, 0x7a, 0x52, 0xf7, 0x61, 0xce, 0xb3, 0xf9,
	0x12, 0x6f, 0xe2, 0x8b, 0x91, 0x05, 0x82, 0x67, 0xb0, 0xf7, 0xc6, 0x0e, 0x7e, 0x8f, 0x85, 0x9a,
	0x24, 0xa4, 0x07, 0x3b, 0x22, 0xf1, 0x9d, 0xbe, 0x33, 0xe8, 0xd0, 0x1d, 0x91, 0x90, 0x43, 0xd8,
	0xcd, 0xb1, 0x50, 0xb1, 0x48, 0xfc, 0x1d, 0x23, 0xb6, 0x72, 0x03, 0x06, 0xbf, 0x1c, 0xf0, 0x36,
	0xac, 0x5b, 0xc6, 0x73, 0x68, 0xe3, 0x3c, 0x8f, 0x35, 0x6d, 0x9c, 0xde, 0xf0, 0x20, 0xdc, 0x9c,
	0x5f, 0x15, 0xe9, 0x2e, 0xce, 0x73, 0xd3, 0xe1, 0x18, 0x3a, 0xf6, 0xf1, 0x7a, 0x58, 0xc3, 0x34,
	0x6a, 0x5b, 0x61, 0x92, 0x90, 0x47, 0xd0, 0x2b, 0x8b, 0x66, 0x9d, 0x0c, 0xfd, 0x66, 0xdf, 0x19,
	0xec, 0xd1, 0xae, 0x55, 0x75, 0x83, 0x77, 0xa8, 0x5b, 0x14, 0x88, 0xca, 0x4e, 0x75, 0xfb, 0xce,
	0xa0, 0x4d, 0xdb, 0x5a, 0x30, 0xfd, 0x5f, 0x41, 0xaf, 0x1a, 0x1a, 0x4b, 0xc5, 0x94, 0xf4, 0x5b,
	0x66, 0xaf, 0xe3, 0x7b, 0xf7, 0xb2, 0x08, 0xed, 0x96, 0xdb, 0x7d, 0xd0, 0x5f, 0xc1, 0x73, 0xe8,
	0x6e, 0xbc, 0x59, 0x92, 0x53, 0x70, 0x85, 0xe2, 0x2b, 0xe9, 0x3b, 0xfd, 0xc6, 0xc0, 0x1b, 0xee,
	0x87, 0x36, 0xef, 0x70, 0x03, 0xa2, 0x96, 0x08, 0xbe, 0x37, 0x6e, 0xa3, 0xbe, 0x34, 0x2b, 0x6f,
	0x25, 0x76, 0x02, 0x5e, 0xc2, 0x14, 0xcb, 0x99, 0x5a, 0x54, 0x71, 0x37, 0x29, 0x54, 0xd2, 0x24,
	0x21, 0xa7, 0xd0, 0x4c, 0xb8, 0x9c, 0x99, 0x6c, 0xee, 0x8b, 0x53, 0x17, 0xa9, 0x41, 0xc8, 0x04,
	0xfe, 0x97, 0x37, 0x42, 0xcd, 0x16, 0xf1, 0x9c, 0x33, 0x75, 0x5d, 0x70, 0x69, 0xf2, 0xf2, 0x86,
	0xfd, 0x2d, 0xd7, 0x1d, 0x8e, 0xf6, 0xac, 0x70, 0x55, 0x7e, 0xeb, 0xe4, 0x4d, 0xa6, 0x7f, 0x6f,
	0xe3, 0x9a, 0x95, 0xbb, 0x5a, 0xbd, 0xac, 0xee, 0xf3, 0x14, 0x5c, 0x9d, 0x9a, 0xf4, 0x3f, 0xff,
	0x3b, 0x8a, 0x71, 0xe7, 0xe7, 0xef, 0x1f, 0x0f, 0x9b, 0xfa, 0xd9, 0xd4, 0xd2, 0xe4, 0x1c, 0x5c,
	0xbd, 0x8b, 0xf4, 0xbf, 0x38, 0x66, 0x3d, 0x52, 0x5b, 0xef, 0x4a, 0x97, 0xc6, 0xae, 0x76, 0xfd,
	0x47, 0x2d, 0x48, 0x46, 0xd0, 0x5a, 0x71, 0xc5, 0x0b, 0xe9, 0x7f, 0xb5, 0x96, 0xfd, 0x9a, 0xe5,
	0xad, 0xa9, 0x55, 0x9e, 0x12, 0x25, 0x2f, 0xc1, 0x33, 0x40, 0x5a, 0xe0, 0x75, 0x2e, 0xfd, 0x6f,
	0xd6, 0x79, 0xb8, 0x35, 0xec, 0xb5, 0xa9, 0x57, 0x6e, 0x98, 0xdf, 0x4a, 0xc1, 0x0b, 0xe8, 0xd5,
	0xae, 0x27, 0xc9, 0xe3, 0xfa, 0xed, 0x0f, 0xee, 0x3c, 0xd8, 0x62, 0xe5, 0xf5, 0xc7, 0x4f, 0x3e,
	0x0e, 0x53, 0xcc, 0x3f, 0xa5, 0xa1, 0xc8, 0xa2, 0x64, 0xca, 0x44, 0x36, 0x2d, 0xc4, 0xd9, 0x4c,
	0xf0, 0x8c, 0x45, 0xd6, 0x76, 0x66, 0x7f, 0xd1, 0x70, 0x7d, 0x11, 0xa5, 0x58, 0x6a, 0xd3, 0x96,
	0x11, 0x47, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xfe, 0xd4, 0xbe, 0x2b, 0x04, 0x00, 0x00,
}
